[2023-09-17T18:48:02.529+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.dbtRun manual__2023-09-17T14:17:43.647960+00:00 [queued]>
[2023-09-17T18:48:02.539+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.dbtRun manual__2023-09-17T14:17:43.647960+00:00 [queued]>
[2023-09-17T18:48:02.540+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-09-17T18:48:02.556+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): dbtRun> on 2023-09-17 14:17:43.647960+00:00
[2023-09-17T18:48:02.561+0000] {standard_task_runner.py:57} INFO - Started process 517 to run task
[2023-09-17T18:48:02.563+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl', 'dbtRun', 'manual__2023-09-17T14:17:43.647960+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp2sya4yde']
[2023-09-17T18:48:02.566+0000] {standard_task_runner.py:85} INFO - Job 158: Subtask dbtRun
[2023-09-17T18:48:02.607+0000] {task_command.py:415} INFO - Running <TaskInstance: etl.dbtRun manual__2023-09-17T14:17:43.647960+00:00 [running]> on host 34065565226b
[2023-09-17T18:48:02.837+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='dbtRun' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T14:17:43.647960+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-17T14:17:43.647960+00:00'
[2023-09-17T18:48:02.838+0000] {logging_mixin.py:151} INFO - Executando o comando <cd /opt/***/dbt/etl && dbt run -t prod>
[2023-09-17T18:48:06.989+0000] {logging_mixin.py:151} INFO - Resultado: 18:48:05  Running with dbt=1.6.2
18:48:06  Encountered an error:
Runtime Error
  Credentials in profile "despesas", target "prod" invalid: '5432' is not of type 'integer'
[2023-09-17T18:48:06.989+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-17T18:48:06.999+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl, task_id=dbtRun, execution_date=20230917T141743, start_date=20230917T184802, end_date=20230917T184806
[2023-09-17T18:48:07.042+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-17T18:48:07.058+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
