[2023-09-17T21:50:35.573+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.dbtRun manual__2023-09-17T21:45:25.685736+00:00 [queued]>
[2023-09-17T21:50:35.583+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.dbtRun manual__2023-09-17T21:45:25.685736+00:00 [queued]>
[2023-09-17T21:50:35.583+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-17T21:50:35.597+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): dbtRun> on 2023-09-17 21:45:25.685736+00:00
[2023-09-17T21:50:35.602+0000] {standard_task_runner.py:57} INFO - Started process 7346 to run task
[2023-09-17T21:50:35.604+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl', 'dbtRun', 'manual__2023-09-17T21:45:25.685736+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpm518608w']
[2023-09-17T21:50:35.607+0000] {standard_task_runner.py:85} INFO - Job 160: Subtask dbtRun
[2023-09-17T21:50:35.649+0000] {task_command.py:415} INFO - Running <TaskInstance: etl.dbtRun manual__2023-09-17T21:45:25.685736+00:00 [running]> on host 34065565226b
[2023-09-17T21:50:35.865+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='dbtRun' AIRFLOW_CTX_EXECUTION_DATE='2023-09-17T21:45:25.685736+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-17T21:45:25.685736+00:00'
[2023-09-17T21:50:35.867+0000] {logging_mixin.py:151} INFO - Executando o comando <cd /opt/***/dbt/etl && dbt run -t prod>
[2023-09-17T21:50:39.901+0000] {logging_mixin.py:151} INFO - Resultado: 21:50:38  Running with dbt=1.6.2
21:50:38  Encountered an error:
Runtime Error
  Credentials in profile "despesas", target "prod" invalid: '5432' is not of type 'integer'
[2023-09-17T21:50:39.901+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-09-17T21:50:39.910+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl, task_id=dbtRun, execution_date=20230917T214525, start_date=20230917T215035, end_date=20230917T215039
[2023-09-17T21:50:39.961+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-09-17T21:50:39.981+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
